#!/bin/sh
# SSH into the Cubie. Usage: tools/cubie-ssh [command...]
#   CUBIE_HOST  address of the Cubie (default: radxa-cubie-a7z.local)
#   CUBIE_KEY   optional private key to use
HOST="${CUBIE_HOST:-radxa-cubie-a7z.local}"
set -- -o StrictHostKeyChecking=accept-new -o ConnectTimeout=8 ${CUBIE_KEY:+-i "$CUBIE_KEY" -o IdentitiesOnly=yes} "radxa@$HOST" "$@"
exec ssh "$@"
