#!/bin/sh
# SSH into the MiSTer as root. Usage: tools/mister-ssh [command...]
#   MISTER_HOST  address of the MiSTer (required)
#   MISTER_KEY   optional private key to use
: "${MISTER_HOST:?set MISTER_HOST to the IP address or hostname of your MiSTer}"
set -- -o StrictHostKeyChecking=accept-new -o ConnectTimeout=8 ${MISTER_KEY:+-i "$MISTER_KEY" -o IdentitiesOnly=yes} "root@$MISTER_HOST" "$@"
exec ssh "$@"
